// <auto-generated />
using System;
using HuylebronVilla.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HuylebronVilla.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250111100900_changeVillaToDb")]
    partial class changeVillaToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HuylebronVilla.Domain.Entities.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Trải nghiệm bể bơi vô cực với phong cách hoàng gia, mang lại sự thư giãn đỉnh cao cùng không gian sang trọng.",
                            Name = "Royal Infinity Pool Villa",
                            Occupancy = 4,
                            Price = 200.0,
                            Sqft = 550
                        },
                        new
                        {
                            Id = 2,
                            Description = "Một thiên đường nghỉ dưỡng với bể bơi riêng và thiết kế hiện đại, mang đến sự thoải mái và tiện nghi tuyệt đối.",
                            Name = "Premium Paradise Villa",
                            Occupancy = 4,
                            Price = 300.0,
                            Sqft = 550
                        },
                        new
                        {
                            Id = 3,
                            Description = "Hòa mình vào thiên nhiên với căn villa hướng biển sang trọng, nơi sự xa hoa và tầm nhìn tuyệt đẹp kết hợp hoàn hảo.",
                            Name = "Luxury Oceanfront Villa",
                            Occupancy = 4,
                            Price = 400.0,
                            Sqft = 750
                        },
                        new
                        {
                            Id = 4,
                            Description = "Căn villa thân thiện với môi trường, được bao quanh bởi cây xanh và không gian yên bình, lý tưởng để tái tạo năng lượng.",
                            Name = "Eco Retreat Villa",
                            Occupancy = 2,
                            Price = 180.0,
                            Sqft = 500
                        },
                        new
                        {
                            Id = 5,
                            Description = "Thưởng ngoạn cảnh quan núi non hùng vĩ ngay từ căn villa ấm cúng, nơi bạn có thể cảm nhận sự yên tĩnh và thanh bình.",
                            Name = "Mountain View Haven",
                            Occupancy = 3,
                            Price = 250.0,
                            Sqft = 600
                        },
                        new
                        {
                            Id = 6,
                            Description = "Ngắm nhìn hoàng hôn tuyệt đẹp từ căn villa với không gian mở, mang đến cảm giác thư thái và lãng mạn khó quên.",
                            Name = "Sunset Serenity Villa",
                            Occupancy = 2,
                            Price = 220.0,
                            Sqft = 520
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
